name = "alisha-portfolio"
type = "javascript"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

[build]
command = "npm run build"
[build.upload]
format = "directory"
dir = "out"

[build.environment]
NODE_VERSION = "18.18.0"
